feat: add creditcal app #10
youngeek-0410/barifac pull request #11
Opened 2021-09-26 10:31 UTC by kathmandu777

# Overview 
setup creditcal app

# Issue number 
Close #10 

# How to check the revision

# Points for Review 

# Remarks 
アプリ名をどうするか
barifacにしようと思ったけどリポジトリ名と被って変な感じするからcreditcalにした
どうでしょうか？

2021-09-26 12:43 UTC, lemonadern approved these changes
~~Credit Cal
LGTM~~

2021-09-26 12:52 UTC, lemonadern requested changes
Credit Calcのほうがいいかも

2021-09-26 12:54 UTC, kathmandu777 commented
credit or credits
cal => calc

2021-09-26 12:54 UTC, kathmandu777 commented
@Chaha1n

2021-09-26 12:58 UTC, Chaha1n commented
複数形のほうが良さそうだけど(単位は当然複数あるので)、いっそCreCaぐらいまで縮めても良いかなとも思ってる。

2021-09-26 13:00 UTC, kathmandu777 commented
@Chaha1n 
どんな処理をするアプリなのか名前から想像つきやすいほうが個人的にはうれしい

2021-09-26 13:03 UTC, kathmandu777 commented
creditscalcにしようかな

2021-09-26 13:04 UTC, Chaha1n commented
思想の問題だしOwnerは僕ではないので最終的にはお任せするけれど、プロダクトの名前と違って開発メンバー内部で呼ぶだけの名前(だよね)だし、名前から想像がつきやすいという点はあまり重要ではないのかなと思う。分からないけど。

2021-09-26 13:05 UTC, Chaha1n commented
それはそれとしてcreditscalcは良い名前だと思います

2021-09-27 02:12 UTC, lemonadern approved these changes
😎

2021-09-27 02:38 UTC, merged