Frontend setup
youngeek-0410/barifac pull request #17
Opened 2021-11-23 04:42 UTC by Dz0526

# Overview 
front の開発環境を整える
- eslint
- prettier&vscode

front プロジェクトスタート
- start next project
- welcome page
- User model

# Issue number 
Close #16 

# How to check the revision

# Points for Review 

# Remarks 

![Welcome](https://user-images.githubusercontent.com/53589227/142972164-91592f87-fd84-49e9-b6c2-b4140af62fd0.png)

2021-11-23 08:12 UTC, kathmandu777 commented on frontend/src/domains/UserFactory.ts
> +      obj.id,
uuidが返却されます

2021-11-25 13:58 UTC, Dz0526 commented on frontend/src/domains/UserFactory.ts
> +      obj.id,
修正

2021-11-26 10:47 UTC, yuta0709 requested changes

2021-11-26 10:47 UTC, yuta0709 commented on frontend/src/domains/User.ts
> +    public uid: number,
uidはstring

2021-11-26 11:07 UTC, Dz0526 commented on frontend/src/domains/User.ts
> +    public uid: number,
修正

2021-11-26 11:21 UTC, yuta0709 approved these changes
LGTM

2021-11-26 11:22 UTC, merged